vaadin/spreadsheet

- assembly/release-notes.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/399)
> Update release notes for 1.3.0.alpha1

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ItemFilter.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/BigExcelFileTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/407)
> Change ItemFilter to use V8 optionGroup

- vaadin-spreadsheet-charts/src/main/java/com/vaadin/addon/spreadsheet/charts/converter/xssfreader/ChartStylesReader.java
Fixes #383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/412)
> Handle files without theme info

- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/SpreadsheetDemoUI.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/413)
> Change to use v8 checkbox in DemoUI

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellSelectionManager.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/SpreadsheetCustomEditorsTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/TestableUI.java
Fixes #359
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/416)
> Correctly generate components to the right of a merged cell

- assembly/release-notes.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/417)
> Updated release notes for 1.3

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/418)
> Update vaadin version to 7.7.4

- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/419)
> Update version to 2.0-SNAPSHOT

- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/420)
> Update version to 1.3-SNAPSHOT

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/Cell.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
Fixes #386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/422)
> New class to use as key for cellvalue and cellstyle in witdth cache

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ItemFilter.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataProvider.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/SpreadsheetDemoUI.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/CustomComponentFixture.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/PopupButtonFixture.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/TablePopupButtonFixture.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/427)
> Update to vaadin8.alpha7

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/PopupButton.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetTable.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetUtil.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/SheetFilterTableTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/SheetTabSheetTest.java
Fixes #428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/431)
> Use correct key for sheetPopupButtons

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetTable.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/SheetFilterTableTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/SheetTabSheetTest.java
Fixes #428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/432)
> Use always absolute reference as key for sheetPopupButtons

- assembly/release-notes.html
- documentation/chapter-spreadsheet.asciidoc
- documentation/spreadsheet-migration-vaaadin8.asciidoc
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet-testbench-api/src/main/java/com/vaadin/addon/spreadsheet/elements/SheetCellElement.java
- vaadin-spreadsheet-testbench-api/src/main/java/com/vaadin/addon/spreadsheet/elements/SheetHeaderElement.java
- vaadin-spreadsheet-testbench-api/src/main/java/com/vaadin/addon/spreadsheet/elements/SpreadsheetElement.java
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/CustomComponentsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/434)
> Add vaadin 8 migration guide to docs

- assembly/release-notes.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/433)
> Update testbench version and release notes

- assembly/release-notes.html
- documentation/spreadsheet-overview.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/435)
> Remove old limitation from docs

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ItemFilter.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/AbstractSpreadsheetTestCase.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/FormulaFieldFormatTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/FormulaFormatTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/GeneralRoundingTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/GeneralSmallRoundingTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/GenericTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/NumberFormatTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataProvider.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/SpreadsheetDemoUI.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/439)
> Update to Vaadin Framework 8.0.0.alpha8

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ItemFilter.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/SpreadsheetDemoUI.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/CustomComponentFixture.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/PopupButtonFixture.java
Also fix java warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/441)
> Update to 8.0.0.alpha9

- assembly/README.txt
- documentation/spreadsheet-charts-integration.asciidoc
- documentation/spreadsheet-installation.asciidoc
- documentation/spreadsheet-quickstart.asciidoc
- documentation/spreadsheet-tutorial.asciidoc
- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
Closes #438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/443)
> Change groupId to 'com.vaadin'

- documentation/spreadsheet-installation.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/445)
> Fix duplicated anchors

- assembly/release-notes.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/447)
> Add release notes about strict OOXML

- documentation/spreadsheet-installation.asciidoc
- vaadin-spreadsheet-charts/src/main/java/com/vaadin/addon/spreadsheet/charts/converter/xssfreader/BarSeriesReader.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/446)
> Prevent NPE if configuration is missing

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet-testbench-api/src/main/java/com/vaadin/addon/spreadsheet/elements/SheetCellElement.java
- vaadin-spreadsheet-testbench-api/src/main/java/com/vaadin/addon/spreadsheet/elements/SheetHeaderElement.java
- vaadin-spreadsheet-testbench-api/src/main/java/com/vaadin/addon/spreadsheet/elements/SpreadsheetElement.java
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/UndoRedoTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/449)
> Update dependencies to beta1

- vaadin-spreadsheet-charts/src/main/java/com/vaadin/addon/spreadsheet/charts/converter/xssfreader/BarSeriesReader.java
PR for version branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/450)
> Prevent NPE if configuration is missing (#446)

- assembly/release-notes.html
- documentation/spreadsheet-overview.asciidoc
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java
Closes #397
Cherry picked from 3a366a1 and cc4ccee
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/457)
> Throw IOException with open strict OOXML files

- documentation/spreadsheet-installation.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/458)
> Fix duplicated anchors (#445)

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SheetChartWrapper.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/SpreadsheetDemoUI.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/CustomComponentFixture.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/467)
> Update to FW8 Charts4 and TB5

- documentation/spreadsheet-quickstart.asciidoc
- documentation/spreadsheet-tutorial.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/468)
> Update tutorial and quickstart to vaadin 8 and SS2

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellSelectionManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/470)
> JavaDoc fixed

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/FormulaFormatter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetStyleFactory.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetTable.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetUtil.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetHandler.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/shared/SpreadsheetState.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/UndoRedoTest.java
Errors are preventing javadoc jar generation
Fixes #117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/479)
> Fix javadoc errors

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ItemFilter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFilterTable.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/482)
> Fix defaults for vertical layout margin in filter overlay

- assembly/release-notes.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/497)
> Update release notes for 1.3.2

- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CustomDataFormatter.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/542)
> Fix javadoc errors and force javadoc verify

- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CustomDataFormatter.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/543)
> Add addons repo for deploy

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetHandlerImpl.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetHandler.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetHandler.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/RowHeaderDoubleClickTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/RowHeaderDoubleClickFixture.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/fixtures/TestFixtures.java
Port #545 to master branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/560)
> Double-click on row resize handle event support (#545)

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CustomDataFormatter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/FormulaFormatter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetStyleFactory.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetTable.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetUtil.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetHandler.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/shared/SpreadsheetState.java
This will enforce valid javadoc and make 1.3 PR easier to port
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/562)
> Fix javadoc issues in 1.3 branch

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/AbstractSpreadsheetTestCase.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/CellsStylePerformanceTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/CopyPasteCellsTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/GroupingPerformanceTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/UndoRedoTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/563)
> Update testbench to 5.1

- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/572)
> Update to next minor

- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/574)
> Bump version to next minor 2.1

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/Cell.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/SpreadsheetDemoUI.java
* fixes #190
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/581)
> Consider filter popup button width when autofitting columns (#481)

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
Pick the changes made in the 1.x branch (f0a4e8d) into the master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/582)
> Add extra padding when autofitting columns (adds to the commit 3873d0d)

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/605)
> code formatting fixes after merging the external PR #600

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/DefaultHyperlinkCellClickHandler.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/Cell.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
* only measureValueWidth if column width is greater than 0
* Consider hidden rows and cols in getRealEventTargetCell
* Prevent NPE with links without address
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/609)
> fix a number of performance issues (mainly with IE11)

- documentation/spreadsheet-tutorial.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/616)
> Fix mvn dependency snippet

- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/SheetFilterTableTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/625)
> Improve stability of filter_removeTable_hideFilter

- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/624)
> update Vaadin version to 7.7.11 (latest)

- vaadin-spreadsheet/pom.xml
Reverts vaadin/spreadsheet#624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/626)
> Revert "update Vaadin version to 7.7.11 (latest)"

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/DefaultHyperlinkCellClickHandler.java
fix a regression introduced in the PR #561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/630)
> fix the issue when click on a hyperlink did not select the target cell

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
http://vaadin.com/nexus -> https://tools.vaadin.com/nexus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/632)
> update the Vaadin Addons Nexus URLs

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
Fixes #553 (SHEET-332)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/637)
> Prevent duplicates of dynamic styles on sheets with overlays

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/AbstractSpreadsheetTestCase.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/638)
> Update testbench version

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
* Prevent duplicates of dynamic styles on sheets with overlays
Fixes #553 (SHEET-332)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/639)
> Prevent duplicates of dynamic styles on sheets with overlays (#637)

- vaadin-spreadsheet-charts/src/test/java/com/vaadin/spreadsheet/charts/interactiontests/InteractionTBTest.java
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ColorConverter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/HSSFColorConverter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/IncrementalStyleBuilder.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetStyleFactory.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/XSSFColorConverter.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingBasedOnFormulaTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingBasedOnSharedFormulaTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingCellValueIsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/648)
> Update POI to 3.17

- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ColorConverter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/HSSFColorConverter.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/IncrementalStyleBuilder.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetStyleFactory.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/XSSFColorConverter.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingBasedOnFormulaTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingBasedOnSharedFormulaTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingCellValueIsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/672)
> 1.5: Update poi to 3.17 and bump version in pom

- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/673)
> Updated framework version for 7.7.14

- vaadin-spreadsheet/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/682)
> Update repo url

- README.md
Added instructions for building without running tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/688)
> Updated setting up instructions

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
The issue can be tested manually. Instructions are in #691 
Fixes #691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/693)
> Fix NPE on widget clean

- documentation/spreadsheet-overview.asciidoc
https://gitlab.vaadin.com/vaadincom/webpage/issues/4656
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/704)
> Trial time was updated to 14-days instead of 30

- documentation/spreadsheet-overview.asciidoc
* Trial time was updated to 14-days instead of 30
https://gitlab.vaadin.com/vaadincom/webpage/issues/4656
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/705)
> Trial time was updated to 14-days instead of 30 (#704)

- assembly/README.txt
- documentation/spreadsheet-charts-integration.asciidoc
- documentation/spreadsheet-installation.asciidoc
- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
Related to vaadin/platform#766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/708)
> Use https for Maven repositories

- assembly/README.txt
- documentation/spreadsheet-charts-integration.asciidoc
- documentation/spreadsheet-installation.asciidoc
- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/CopyPasteTextBox.java
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/CopyPasteCellLayoutSizeFullTest.java
- vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/EmptySpreadsheetSizeFullUI.java
I believe it can be merged with "_rebase and merge_" to preserve history.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/709)
> Cherry pick #707 and #708

- documentation/spreadsheet-tutorial.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/spreadsheet/711)
> Update Spreadsheet to 2.1.1

- .gitignore
- flow-gwtexporter/src/main/java/com/google/gwt/dev/shell/CheckForUpdates.java
- pom.xml
related to #728 
This upgrades all versions but POI and Lit that will be in separated PRs
> Bump versions

- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
> fix: declare variable in JSNI so as final bundle can be imported

- vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Serializer.java
fixes: #746
This fix increases performance by reducing loading of `cell_styles_performance.xlsx` from 85 secs to 2
> fix: improve serializer performance for maps

- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/CellComment.java
- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/PopupButtonWidget.java
- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SelectionWidget.java
- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetOverlay.java
- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js
> fix: added a classed overlay to host context-menu and comments for correctly applying styles

- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetConnector.java
> fix: assure that comment maps are initialized before using them

- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java
> fix: avoid out of bound errors when editing formulas

- vaadin-spreadsheet-flow/pom.xml
> fix: remove repeated classes from classpath

- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/OverlayInfo.java
- vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/client/OverlayInfo.java
> fix: overlay-info object was not serialized correctly

- .gitignore
- pom.xml
- vaadin-spreadsheet-flow-integration-tests/pom.xml
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/AbstractSpreadsheetIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CommentIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ConditionalFormattingBasedOnFormulaIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ConditionalFormattingBasedOnSharedFormulaIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ConditionalFormattingCellValueIsIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ConditionalFormattingIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ConditionalFormattingOnCellDeletionIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ContextMenuIT.java
- vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/CreateNewIT.java
> Move integration tests [part 2]

- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
> fix: scroll position should consider size of the frozen panel

- pom.xml
- vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- vaadin-spreadsheet-flow/pom.xml
- vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/framework/Action.java
> chore: Fix javadoc errors

- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java
> fix: avoid out-of-index exception when parsing ranges in formulas (CP 1.5)

- vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java
> fix: avoid out-of-index exception when parsing ranges in formulas (CP master)

- vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/spreadsheet-styles-valo.css
> fix: set higher zindex to cellinput and sheet-tabsheet-options

- vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java
> feat!: disable popupButtons until table-support is implemented

- pom.xml
- vaadin-spreadsheet-charts/pom.xml
- vaadin-spreadsheet-testbench-api/pom.xml
- vaadin-spreadsheet/pom.xml
Reverts vaadin/spreadsheet#843
> Revert "chore: Updates for modern Eclipse compatibility with Java 11"
